// <auto-generated />
using System;
using API_SeeManga.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_SeeManga.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_SeeManga.Models.Model.CapitulosModel", b =>
                {
                    b.Property<int>("ID_CAPITULOS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_MANGA")
                        .HasColumnType("int");

                    b.Property<int>("NUMERO")
                        .HasColumnType("int");

                    b.Property<int>("QT_CAPITULOS")
                        .HasColumnType("int");

                    b.HasKey("ID_CAPITULOS");

                    b.HasIndex("ID_MANGA");

                    b.ToTable("Capitulos");
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.ComentariosModel", b =>
                {
                    b.Property<int>("ID_COMENTARIOS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMENTARIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("ID_MANGA")
                        .HasColumnType("int");

                    b.Property<int>("ID_USUARIO")
                        .HasColumnType("int");

                    b.HasKey("ID_COMENTARIOS");

                    b.HasIndex("ID_MANGA");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.GenerosModel", b =>
                {
                    b.Property<int>("ID_GENERO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NM_GENERO")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ID_GENERO");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.Manga_GenerosModel", b =>
                {
                    b.Property<int>("ID_GENERO")
                        .HasColumnType("int");

                    b.Property<int>("ID_MANGA")
                        .HasColumnType("int");

                    b.HasKey("ID_GENERO", "ID_MANGA");

                    b.HasIndex("ID_MANGA");

                    b.ToTable("Manga_Generos");
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.MangasModel", b =>
                {
                    b.Property<int>("ID_MANGA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("CAPA")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ID_SITUACAO")
                        .HasColumnType("int");

                    b.Property<string>("SINOPSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(2500)")
                        .HasMaxLength(2500);

                    b.Property<string>("TITULO")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID_MANGA");

                    b.HasIndex("ID_SITUACAO");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.PaginasModel", b =>
                {
                    b.Property<int>("ID_PAGINAS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_CAPITULOS")
                        .HasColumnType("int");

                    b.Property<int>("NUMERO")
                        .HasColumnType("int");

                    b.Property<byte[]>("PAGINA")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID_PAGINAS");

                    b.HasIndex("ID_CAPITULOS");

                    b.ToTable("Paginas");
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.SituacoesModel", b =>
                {
                    b.Property<int>("ID_SITUACAO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SITUACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ID_SITUACAO");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.CapitulosModel", b =>
                {
                    b.HasOne("API_SeeManga.Models.Model.MangasModel", "Manga")
                        .WithMany("Capitulos")
                        .HasForeignKey("ID_MANGA")
                        .HasConstraintName("FK_CAPITULOS_MANGA")
                        .IsRequired();
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.ComentariosModel", b =>
                {
                    b.HasOne("API_SeeManga.Models.Model.MangasModel", "Manga")
                        .WithMany("Comentarios")
                        .HasForeignKey("ID_MANGA")
                        .HasConstraintName("FK_COMENTARIOS_MANGA")
                        .IsRequired();
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.Manga_GenerosModel", b =>
                {
                    b.HasOne("API_SeeManga.Models.Model.GenerosModel", "Genero")
                        .WithMany("Manga_generos")
                        .HasForeignKey("ID_GENERO")
                        .HasConstraintName("FK_MANGA_GENEROS_GENERO")
                        .IsRequired();

                    b.HasOne("API_SeeManga.Models.Model.MangasModel", "Manga")
                        .WithMany("Manga_generos")
                        .HasForeignKey("ID_MANGA")
                        .HasConstraintName("FK_MANGA_GENEROS_MANGA")
                        .IsRequired();
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.MangasModel", b =>
                {
                    b.HasOne("API_SeeManga.Models.Model.SituacoesModel", "Situacao")
                        .WithMany("Mangas")
                        .HasForeignKey("ID_SITUACAO")
                        .HasConstraintName("FK_MANGA_SITUACAO")
                        .IsRequired();
                });

            modelBuilder.Entity("API_SeeManga.Models.Model.PaginasModel", b =>
                {
                    b.HasOne("API_SeeManga.Models.Model.CapitulosModel", "Capitulo")
                        .WithMany("Paginas")
                        .HasForeignKey("ID_CAPITULOS")
                        .HasConstraintName("FK_PAGINAS_CAPITULOS")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
